on:
  pull_request:
  merge_group:

name: defmt-rtt-prio

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: stable
            target: thumbv6m-none-eabi
            features: prio_bits_2
          - rust: stable
            target: thumbv7em-none-eabihf
            features: prio_bits_4
          - rust: stable
            target: thumbv8m.main-none-eabihf
            features: prio_bits_4

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true

      - name: Format
        run: cargo fmt
      - name: Regular build
        run: cargo check --target ${{ matrix.target }} --features ${{ matrix.features }}
      - name: Clippy
        run: cargo clippy --target ${{ matrix.target }} --features ${{ matrix.features }}
